version: '3.8'

services:

  reservationmicroservice:
    image: reirasdev/reservationmicroservice:${IMAGE_TAG}
    restart: always
    environment:
      TZ: America/São_Paulo
    ports:
      - 8080:8080