version: '3.8'

services:

  reservationmicroservice:
    image: reirasdev/reservationmicroservice:${IMAGE_TAG}
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: net-reservationmicroservice